### PR TITLE
Update Esbuild Version to 0.14.29

### PR DESCRIPTION
**Pull request by kinson**
# Overview

I was taking a look at #38 and noticed the the esbuild version has not been incremented since 0.14.0. I put this pr together quickly in case it would be beneficial to update the latest esbuild version to [0.14.29](https://github.com/evanw/esbuild/releases/tag/v0.14.29).

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! I will merge this but note those numbers have to be updated on Phoenix mix phx.new too (and perhaps updating on Phoenix is the most important!). :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by kinson** [comment]
@josevalim Thanks for the heads up, I put together a quick branch with these changes on the Phoenix project.

Before I create a pr I want to walk through the new project setup and makes sure esbuild works with this update as expected and the guides are still up to date. 

However, if there are other changes that I missed in this branch (and you have a spare moment to check), let me know: https://github.com/phoenixframework/phoenix/compare/master...kinson:master !

❤️‍🔥 ❤️‍🔥 ❤️‍🔥

**Comment by josevalim** [comment]
That looks good to me! Please PR and cc me once you are ready!

**Pull request merged**
