### PR TITLE
Update latest known version

### PR DESCRIPTION
**Pull request by cw789**
I was thinking about creating an maintenance task or a test against the public NPM API.
But probably the comment for the API is all we need for now.

### CODE REVIEW

**Comment by josevalim** [comment]
We have to change other files. It is easier to grep the codebase for the old version and then replace everything (including README).

**Comment by cw789** [comment]
Alright. Feel free to close.
But I don't understand exactly why tests are failing now.

**Comment by cw789** [comment]
There is something wrong if latest known version and configured version is different.

**Comment by josevalim** [comment]
Yes, you need to update 0.12.18 by 0.12.26 everywhere in the codebase, including `config/` files. :)

**Comment by cw789** [comment]
Okay, I'll take it that way.
But I'm not understanding why or what does race or skip installation in the tests if the versions are different.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
